{% set name = "llama-index-workflows" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_workflows-{{ version }}.tar.gz
  sha256: 916ae77b22f2589b515a10b49f2fa519dd41c224d85710f99c54797d71b3c494

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - eval-type-backport >=0.2.2
    - llama-index-instrumentation >=0.1.0
    - pydantic >=2.11.5

test:
  imports:
    - workflows
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/run-llama/llama_index
  summary: An event-driven, async-first, step-based way to control the execution flow of AI applications like Agents.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
