{% set name = "llama-index-workflows" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_workflows-{{ version }}.tar.gz
  sha256: 07a68cf58040d469af8d05f56217418ae6404557f0254bff22a7481987818e3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - eval-type-backport >=0.2.2
    - llama-index-instrumentation >=0.1.0
    - pydantic >=2.11.5

test:
  imports:
    - workflows
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/run-llama/llama_index
  summary: An event-driven, async-first, step-based way to control the execution flow of AI applications like Agents.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
